# Generated by Django 3.1.3 on 2020-12-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbook',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
